# Make a symlink since helix can't include another config file:
# ln -s /home/syuk/dotfiles/helix/config.toml ~/.config/helix/

theme = "zed_onedark"

[editor]
line-number = "relative"
popup-border = "popup"
bufferline = "multiple"

[editor.whitespace.render]
tab = "all"

[editor.cursor-shape]
insert = "bar"

[keys.insert]
j = { k = "normal_mode" }
