# Make a symlink since helix can't include another config file:
# ln -s $HOME/dotfiles/helix/config.toml ~/.config/helix/

theme = "zed_onedark"

[editor]
line-number = "relative"
popup-border = "popup"
bufferline = "always"

[editor.statusline]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"

[editor.whitespace.render]
tab = "all"

[editor.cursor-shape]
insert = "bar"

[keys.insert]
j = { k = "normal_mode" }

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
